language: node_js
node_js:
- '5.5'
before_install:
  - openssl aes-256-cbc -K $encrypted_0979a39447c2_key -iv $encrypted_0979a39447c2_iv
    -in .npmrc.enc -out .npmrc -d
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq google-chrome-stable
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: npm test
before_deploy: npm run build
deploy:
  provider: npm
  skip_cleanup: true
  email: forrest@sembiki.com
  api_key:
    secure: KwIWPYT125xqr8CWMuMadU5gkh183Klp2lRuyH73q5h0nVH+OzwcxOVWirdCKX6UA3d2cT4fs28OaH58apvlDkqrDyE8j3YENFi7W5fyWr1lQlgNqD4pEIrBXQF1OP9A0yUDE9pZebQ+PiMvQ665qkl2GEKFaYjI/57vDO0jKaDIiGihrAQR1hRCIWGcWxTigq6vagmcYHVS/8udzqqxce6Cx9nJhHzHTc2ARPND0c/h6jySzZIzZCG781j0v0TWwzew20ibIzWhRrqq0l0lDFZD0usRXTzH8Bc6mDPX13jKvXJfm138iX5K/rRoL7lnBi9KTXMANNh/tR++tK4LJDr2226eapOFg6z1mhMAwhSXiDSf/NSbJtQvSKT9vCri4cDglKBqgE9H2PBrgH0FhPYmSzTcD59LQqq3yt5Sa1xKRmjidrmltbK+yjfPShr3huS2Vhj4aFGyIVxVw+YSFwUhTIg9/e6S42REkxS7zIvbNuRHBtlUSpB5ZdqaM7qMcavU8gsm38JRSqxgZR0XcCo5rIrOfG+A80B3xsGxyGf0+jjVv5WUAITDmcPw0GTe5G0H/yOf94FG1YCNLjel4NZUn3eBTghrYtH3WM95D6ua7kSowXs7OTWHLCAWgKk79lKekVhznYHtMyG82Rk9VJfJlav6/l1d85/n3enqymM=
  on:
    tags: true
    repo: the-grid/ed
after_script: bash ./gh-pages.sh
env:
  global:
  - GH_REF: github.com/the-grid/ed.git
  - secure: Pz7NfvRl0OWA1Jmwzjdzt5Ug8TCVw8x44JbmniBhiMooh7/hFAVN9b6RvCWPx/7eqf+uQXiyaFfG9UcXQNwLo9cEkvwWlEyhSW/k7sMMyddl3rOK8zf9PfmoNU9K6Q0t3YPvYOAXTe2Ma43d/4OEJY1JgbtlooDldjhHqQqIiFuPxUhk7rfLdtpfI4mijVt7wjSmY7pPg2jtddRfNFExAk0p4KZOSSQlrn6R9tdIMeSALRfo7oulKheGq0V5CLTaX5OlRojeI5UIrGPJpIk4QbYaN19u6opGetlLzQ1qqyiSs8pDL8XXV55GPyPjB8m4iEJXnAjIDgqc5LTtDdhRpmlti+23xX5GKIto9/uj4TU/knouuAs54lcXgwuyBT+G8MLDsED3Xzpxmw8JmvpKiiilRwn58bT1SZ2BHkJdvB/qnzQQ7G4726OuAo0rsMR3S8eRk3ysnf4Vva+rHtA26zuYeIZlP0GAkZCjs45r56fJVS0hvLqPANBrhZETdxBKOyRo64KAft0ql3oQUpdXmuwY4IbhKDKtYDjlQe3J262wLBnSo878RFWoB6YTvVxojhOv98nc2yuTcUjX8n72fDtnceSFkj4x4pMRmg6a+eAwN0Qq28BwlMm+H1913AGQ3wsVNakwQ5CSWU8C5LuacUd0HOV3q2PfhcroVnWNmhc=
